version: "3.9"

services:
  app:
    image: ${DOCKER_REGISTRY-}bibliotecha
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "BiblioTECHa_Password"
      ACCEPT_EULA: "Y"
    volumes:
      - C:\Dados\Volumes\MSSQL:/var/opt/mssql/data
    ports:
      - "1450:1433"
